modLoader="javafml"
loaderVersion="[31,)"

[[mods]]
modId="the_descending_dimensions"
version="1.0.0"
displayName="The Descending Dimensions"
credits="Created using mod maker MCreator - https://mcreator.net/about"
displayURL="https://mcreator.net"
authors="JumpWatch, MCreator"

[[dependencies.the_descending_dimensions]]
    modId="minecraft"
    mandatory=true
    versionRange="[1.15.2]"
    ordering="NONE"
    side="BOTH"



